[[Bazel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d4099ff6b05fc31c8fdc14710cbe4c5a879aba6"
libc = "musl"
os = "linux"

    [[Bazel.download]]
    sha256 = "fb8e3fe7e7688fb24aa57b9eb62f2087a1ff6442d31585e7c508a5e7ffd1f643"
    url = "https://github.com/JuliaBinaryWrappers/Bazel_jll.jl/releases/download/Bazel-v8.7.0+0/Bazel.v8.7.0.x86_64-linux-musl-cxx11.tar.gz"
