[[Bazel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0e5d1b19235a24a1a470bdd4591f7c099a8944f"
libc = "musl"
os = "linux"

    [[Bazel.download]]
    sha256 = "3ec8875de9a99ffdb239b6b4cde3239f58e5fadcbc261da0173769f42420a43d"
    url = "https://github.com/JuliaBinaryWrappers/Bazel_jll.jl/releases/download/Bazel-v7.7.0+0/Bazel.v7.7.0.x86_64-linux-musl-cxx11.tar.gz"
