# Autogenerated wrapper script for Bazel_jll for x86_64-linux-musl-cxx11
export bazel

JLLWrappers.@generate_wrapper_header("Bazel")
JLLWrappers.@declare_executable_product(bazel)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        bazel,
        "bin/bazel",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
